# Generated by Django 5.0.6 on 2024-08-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='kits/'),
        ),
    ]
