# Generated by Django 5.0.6 on 2024-08-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_web', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='field_name',
            field=models.URLField(blank=True, null=True),
        ),
    ]
